# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LehmanHacks2019' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LehmanHacks2019
  pod 'lottie-ios'
end
